---
driver_plugin: docker
# driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  socket: 'tcp://192.168.42.43:4243'

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default]
  - name: centos-6.4
    run_list:
      - recipe[yum::default]

suites:
  - name: default
    run_list:
      - recipe[skeleton::default]
    attributes:
